package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_HIS".
 */
public class SearchHis {

    private String smitem;

    public SearchHis() {
    }

    public SearchHis(String smitem) {
        this.smitem = smitem;
    }

    public String getSmitem() {
        return smitem;
    }

    public void setSmitem(String smitem) {
        this.smitem = smitem;
    }

}
