package com.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.greendao.SearchHis;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_HIS".
*/
public class SearchHisDao extends AbstractDao<SearchHis, String> {

    public static final String TABLENAME = "SEARCH_HIS";

    /**
     * Properties of entity SearchHis.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Smitem = new Property(0, String.class, "smitem", true, "SMITEM");
    };


    public SearchHisDao(DaoConfig config) {
        super(config);
    }
    
    public SearchHisDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_HIS\" (" + //
                "\"SMITEM\" TEXT PRIMARY KEY NOT NULL );"); // 0: smitem
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_HIS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SearchHis entity) {
        stmt.clearBindings();
 
        String smitem = entity.getSmitem();
        if (smitem != null) {
            stmt.bindString(1, smitem);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SearchHis readEntity(Cursor cursor, int offset) {
        SearchHis entity = new SearchHis( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // smitem
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SearchHis entity, int offset) {
        entity.setSmitem(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(SearchHis entity, long rowId) {
        return entity.getSmitem();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(SearchHis entity) {
        if(entity != null) {
            return entity.getSmitem();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
